### ISSUE TITLE
Support for Java Rx ? 

### ISSUE THREAD

**Issue by rahulravindran0108** [Yelp/yelp-android#25]
Would there also be support for using Java Rx? Seems like a cleaner way to call api for data

I added the following code to YelpAPI.java and also added the necessary libraries.

```
@GET("/v2/business/{businessId}")
    Observable<Business> getBusinessRx(@Path("businessId") String businessId);
```

This way we can use subscriptions for cleaner code at the developer's end

**Comment by tzuhanwu** [comment]
Hi @rahulravindran0108. We do consider to support RxJava in the upcoming updates, I'll update this issue when we get there.

**Comment by tzuhanwu** [comment]
We are tracking this feature internally. Mark as close here.
