### ISSUE TITLE
Upgrade to Retrofit 2.0.0 stable from current beta dependency

### ISSUE THREAD

**Issue by tmelz** [Yelp/yelp-android#26]
https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-200-2016-03-11

**Comment by mittonk** [comment]
Excellent.

**Comment by tzuhanwu** [comment]
Thanks for the notify, @tmelz. Ticket is filed and I'll look into it.

**Comment by tzuhanwu** [comment]
Update: #28 merged Retrofit 2.0.0.
