### ISSUE TITLE
searchResponse.total() is different from searchResponse.businesses().size() ? 

### ISSUE THREAD

**Issue by Nevvea7** [Yelp/yelp-android#34]
If the number of business to return is limited (e.g. params.put("limit", "3");), then searchResponse.businesses().size() will be 3 but searchResponse.total() seems to return the # of businesses that match the criteria without the limit. Is this expected ?

**Comment by tzuhanwu** [comment]
Hello @Nevvea7, 

Yes, it's an expected behavior. "Total" is the number of businesses that matches the searching criteria instead of the number of business results in the response.
