### ISSUE TITLE
YelpAPIFactory error.

### ISSUE THREAD

**Issue by zaneran** [Yelp/yelp-android#35]
YelpAPIFactory error:

java.lang.NoClassDefFoundError: Failed resolution of: Lse/akerfeldt/okhttp/signpost/OkHttpOAuthConsumer;
at com.yelp.clientlib.connection.YelpAPIFactory.<init>(YelpAPIFactory.java:37)

I am sure my CONSUMER_KEY, CONSUMER_SECRET, TOKEN, TOKEN_SECRET are correct.
Can anyone help me with this? Thank you!

**Comment by tzuhanwu** [comment]
Hi @zaneran, it doesn't look like it's related to the credentials, NoClassDefFoundError means it cannot find the OkHttpOAuthConsumer class in your classpath. Yelp-android uses https://github.com/pakerfeldt/okhttp-signpost to sign the request, and OkHttpOAuthConsumer should be downloaded and compiled if your Maven/Gradle configuration is correct. Could you check whether the OkHttpOAuthConsumer class is in your classpath?

**Comment by jbrick** [comment]
Going to close this out, since there haven't been any recent responses.

**Comment by GibranPolonsky** [comment]
Hey, sorry i need to open this again, i still receiving the same issue.
` compile 'com.squareup.okhttp3:okhttp:3.0.1'
 compile 'se.akerfeldt:okhttp-signpost:1.1.0' ANDROID OS 5.1
`

**Comment by mingxino** [comment]
I have encountered the same issue for android ios 4.4.3
