### ISSUE TITLE
InvalidSignature:

### ISSUE THREAD

**Issue by mgujare** [Yelp/yelp-android#36]
seeing the error on async search API callback:
Call<SearchResponse> call = yelpAPI.search(coordinate, queryParams);

public void onFailure(Call<SearchResponse> call, Throwable t) 
this throwable has below message. 

"com.yelp.clientlib.exception.exceptions.InvalidSignature:"

I double checked the yelp credentials and initialization code, they seem correct. Is it known issue ?

**Comment by tzuhanwu** [comment]
@mgujare, you mentioned async search API, do you get the same error when calling the endpoint synchronously?

**Comment by mgujare** [comment]
@tzuhanwu based on some testing i did, there is silent failure for synchronous call made from non ui thread. No response returned. No IO exception either. However async call has above error. Any code snippet / demo app of successful implementation will be appreciated, if you are positive that both calls should work fine. Thanks!

**Comment by mgujare** [comment]
update: Code works with rx libraries that i ended up using. I would like to know if you have any thoughts around that, or any undocumented limitations. But otherwise consider this closed.

**Comment by mgujare** [comment]
@tzuhanwu any recommended pro-guard settings/rules ? i am seeing errors in release build. I played around with some rules...got rid of some errors but still seeing fasterxml jackson related errors.

**Comment by tzuhanwu** [comment]
hi @mgujare, sorry I'm pretty distracted recently. I'll try to get back to you asap for your questions. What's the jackson errors you are seeing?  

We do plan to put out an example so it's easier to integrate.

**Comment by mgujare** [comment]
@tzuhanwu thanks. It will be really appreciated if you can put up a demo with placeholders for credentials(consumer key/ token) These can be added by devs when they build demo project. Particularly useful area is build.gradle for dependencies and proguard rules.
Tips for integration if devs are already using okhttp and rx or other popular dependencies. 

For now i am facing below only in release build..
------------------------------------
09-19 12:06:21.613  7712  8104 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.fasterxml.jackson.annotation.JsonAutoDetect$Visibility com.fasterxml.jackson.annotation.JsonAutoDetect.getterVisibility()' on a null object reference
09-19 12:06:21.613  7712  8104 E AndroidRuntime: 	at com.fasterxml.jackson.databind.f.ar.<init>(Unknown Source)
09-19 12:06:21.613  7712  8104 E AndroidRuntime: 	at com.fasterxml.jackson.databind.f.ar.<clinit>(Unknown Source)

 Class com.fasterxml.jackson.databind.PropertyNamingStrategy$LowerCaseWithUnderscoresStrategy has no default (no arg) constructor
-----------------------------------------------
current pro-guard rules:
 Proguard configuration for Jackson 2.x (fasterxml package instead of codehaus package)

-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}

-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }

-dontwarn com.fasterxml.jackson.databind.**

-keep class org.codehaus.** { *; }
-keep class com.fasterxml.jackson.annotation.** { *; }
-keepclassmembers public final enum org.codehaus.jackson.annotate.JsonAutoDetect$Visibility {
 public static final org.codehaus.jackson.annotate.JsonAutoDetect$Visibility *; }
-keep public class your.class.** {
  public void set*(***);
  public *** get*();
}

# OkHttp
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

**Comment by tzuhanwu** [comment]
I'm not sure about ProGuard, but my simple example app and intergrationTests work for me. For a quick example, it might help for taking a look of the integration tests of this clientlib: https://github.com/Yelp/yelp-android/blob/master/src/integration-test/java/com/yelp/clientlib/BusinessIntegrationTest.java. You should not need to do something too different.

**Comment by jbrick** [comment]
@mgujare  in your ProGuard definitions it looks like you have:

```
-keep public class your.class.* {
public void set(*);
public ** get*();
}
```

'your.class' is a placeholder that probably needs to be filled in with an actual class. Something like:

```
-keepclasseswithmembers class com.yelp.clientlib.entities.** {
  <init>(...);
  public void set*(***);
  public *** get*();
}
```
http://stackoverflow.com/questions/38242650/after-applying-proguard-jackson-skipping-to-parse-json-response-with-root/38243888


@tzuhanwu It would be a good idea to bundle ProGuard rules with the SDK, so that user's of it don't have to worry. Here's an example PR https://github.com/koral--/android-gif-drawable/pull/193/files, once the proper rules are discovered.

**Comment by tzuhanwu** [comment]
@jbrick, thanks for helping on. Filed #37 for the ProGuard integration so we don't forget.

**Comment by mgujare** [comment]
@jbrick thanks. I have seen this SO thread. I eventually managed to create a successful release build with proguard. i have raised a PR for proguard file.
