### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by andrewbwogi** [Yelp/yelp-android#48]
Building a project with Maven dependency:

`<dependency>
 <groupId>io.github.ranga543</groupId>
<artifactId>yelp-fusion-client</artifactId>
<version>0.1.3</version>
</dependency>`

results in the following Maven error:

> The following artifacts could not be resolved: io.github.ranga543:yelp-fusion-client:jar:0.1.2, com.android.support:appcompat-v7:jar:25.1.1: Failure to find io.github.ranga543:yelp-fusion-client:jar:0.1.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Version 0.1.3 and 0.1.2 both result in the same error.

**Comment by elope-developers** [comment]
This is probably due to Yelp making the switch to the new version of the Yelp API. Just takes time for the servers to catch up I think
